# Generated by Django 5.2.5 on 2025-11-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0002_anuncio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='¿Cuál es el problema?')),
                ('descripcion', models.TextField(verbose_name='Detalles del problema')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar exacto (Ej: Baño Piso 1)')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja (Se puede esperar)'), ('media', 'Media (Necesita atención)'), ('alta', 'Alta (Urgente / Peligroso)')], default='media', max_length=10)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=15)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
