# Generated by Django 5.2.5 on 2025-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_reporteproblema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
