# Generated by Django 5.2.5 on 2025-11-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0004_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='¿Es Importante?'),
        ),
    ]
