# Generated by Django 5.2.5 on 2025-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0005_documento_importante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddialibre',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/dias_libres/', verbose_name='Documento de Respaldo (Opcional)'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/vacaciones/', verbose_name='Documento de Respaldo (Opcional)'),
        ),
    ]
