# Generated by Django 5.2.5 on 2025-11-24 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0006_solicituddialibre_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-K (con guion y sin puntos)', regex='^\\d{7,8}-[0-9kK]$')]),
        ),
    ]
