# Generated by Django 5.2.5 on 2025-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0007_alter_perfilusuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddialibre',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00', verbose_name='Fecha de envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00', verbose_name='Fecha de envío'),
            preserve_default=False,
        ),
    ]
