# Generated by Django 5.2.7 on 2025-10-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Empleado', 'Empleado'), ('Subdirector', 'Subdirector'), ('Director', 'Director')], default='Empleado', max_length=20)),
            ],
        ),
    ]
