# Generated by Django 5.2.5 on 2025-10-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('informacion', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='roles_permitidos',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
